const BADGE_URL = (badge: POKEMON_TYPES) => `https://raw.githubusercontent.com/duiker101/pokemon-type-svg-icons/5781623f147f1bf850f426cfe1874ba56a9b75ee/icons/${badge}.svg`

export const enum POKEMON_TYPES {
  GRASS = 'grass',
  FIRE = 'fire',
  WATER = 'water',
  BUG = 'bug',
  NORMAL = 'normal',
  ELECTRIC = 'electric',
  FIGHTING = 'fighting',
  POISON = 'poison',
  GROUND = 'ground',
  FLYING = 'flying',
  PSYCHIC = 'psychic',
  ROCK = 'rock',
  ICE = 'ice',
  GHOST = 'ghost',
  DRAGON = 'dragon',
  DARK = 'dark',
  STEEL = 'steel',
  FAIRY = 'fairy',
}

export const POKEMON_TYPE_BADGES = Object.freeze({
  [POKEMON_TYPES.GRASS]: BADGE_URL(POKEMON_TYPES.GRASS),
  [POKEMON_TYPES.FIRE]: BADGE_URL(POKEMON_TYPES.FIRE),
  [POKEMON_TYPES.WATER]: BADGE_URL(POKEMON_TYPES.WATER),
  [POKEMON_TYPES.BUG]: BADGE_URL(POKEMON_TYPES.BUG),
  [POKEMON_TYPES.NORMAL]: BADGE_URL(POKEMON_TYPES.NORMAL),
  [POKEMON_TYPES.ELECTRIC]: BADGE_URL(POKEMON_TYPES.ELECTRIC),
  [POKEMON_TYPES.FIGHTING]: BADGE_URL(POKEMON_TYPES.FIGHTING),
  [POKEMON_TYPES.POISON]: BADGE_URL(POKEMON_TYPES.POISON),
  [POKEMON_TYPES.GROUND]: BADGE_URL(POKEMON_TYPES.GROUND),
  [POKEMON_TYPES.FLYING]: BADGE_URL(POKEMON_TYPES.FLYING),
  [POKEMON_TYPES.PSYCHIC]: BADGE_URL(POKEMON_TYPES.PSYCHIC),
  [POKEMON_TYPES.ROCK]: BADGE_URL(POKEMON_TYPES.ROCK),
  [POKEMON_TYPES.ICE]: BADGE_URL(POKEMON_TYPES.ICE),
  [POKEMON_TYPES.GHOST]: BADGE_URL(POKEMON_TYPES.GHOST),
  [POKEMON_TYPES.DRAGON]: BADGE_URL(POKEMON_TYPES.DRAGON),
  [POKEMON_TYPES.DARK]: BADGE_URL(POKEMON_TYPES.DARK),
  [POKEMON_TYPES.STEEL]: BADGE_URL(POKEMON_TYPES.STEEL),
  [POKEMON_TYPES.FAIRY]: BADGE_URL(POKEMON_TYPES.FAIRY),
})


